spring:
  messages:
    basename: validationMessages
  datasource:
    url: jdbc:h2:mem:atividade
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
